import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SHEETS_CLIENT_EMAIL,
  key: (process.env.GOOGLE_SHEETS_PRIVATE_KEY ?? "").replace(/\\n/g, "\n"),
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

export async function saveContact(data: {
  name: string;
  email: string;
  message: string;
}) {
  try {
    const doc = new GoogleSpreadsheet(
      process.env.SPREADSHEET_ID ?? "",
      serviceAccountAuth
    );
    await doc.loadInfo();

    const sheet = doc.sheetsByTitle["Contact Form"];
    await sheet.addRow({
      Timestamp: new Date(),
      Name: data.name,
      Email: data.email,
      Message: data.message,
    });
    return true;
  } catch (error: any) {
    console.log("GOOGLE SHEET ERROR", error);
    throw new Error(error.toString());
  }
}
